#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Rockfish command-line interface for working with SEG-Y files.
"""
import sys
import argparse
import warnings
import rockfish

# TODO this is dog slow, think about popping segy i/o stuff out of obspy
#from rockfish.segy.segy import readSEGY

__version__ = rockfish.__version__







class ArgumentParser(argparse.ArgumentParser):
    """
    Base class for the argument parsers.

    Includes options available to all commands and subcommands.
    """
    def __init__(self, *args, **kwargs):
        argparse.ArgumentParser.__init__(self, *args, **kwargs)
        self.add_argument('--version', action='version',
                          version='%(prog)s ' + str(__version__))
        self.subparsers = self.add_subparsers(dest='subcommand',
                                              metavar='<subcommand>',
                                              help='TODO subcommand help')
            
class Rockfish(ArgumentParser):
    """
    Class for the main rockfish command.
    """

    def __init__(self, argv, *args, **kwargs):

        self.parser = ArgumentParser(prog='rockfish',
                                     description='Work with SEG-Y files.')
        self.args = self.parser.parse_args(argv)




if __name__ == '__main__':

    prog = Rockfish(sys.argv[1:])
    #prog.run()
