#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Format doctest results generated by Sphinx.
"""

import os

# Files
raw_doctest = 'build/doctest/output.txt'
formated_doctest = 'source/doctest/index.rst'

# Read results
assert os.path.isfile(raw_doctest),\
        "{:} does not exist, run make doctest to make it.".format(raw_doctest)

fin = open(raw_doctest)

test_items = []
for line in fin:
    line = line.strip('\n')
    if line.startswith('Results of doctest builder run on'):
        test_date = line[34:]
        continue
    if line.startswith('Document: '):
        print line[18:]

        test_items.append({})
        test_items[-1]['file'] = line[18:].replace('.','/') + '.py'
        continue

# Reformat results and write out
if not os.path.isdir(os.path.dirname(formated_doctest)):
    os.mkdir(os.path.dirname(formated_doctest))

fout = open(formated_doctest, 'w')

fout.write("""
.. _doctest-index:

=======
doctest
=======

Rockfish uses :mod:`python.doctest` to run interactive examples.  Here are the results of running these examples in the current code:

""")



